name: Yearly Issue Metrics
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Issue Metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERY: 'repo:holoviz/holoviews is:issue created:2024-01-01..2024-12-31 -label:"duplicate"'

      - name: Check if issue_metrics.md exists
        run: |
          if [ ! -f issue_metrics.md ]; then
            echo "No issues found for the specified query." > issue_metrics.md
          fi

      - name: Create issue from metrics report
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Yearly Issue Metrics Report
          token: ${{ secrets.GH_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: Azaya89
