name: Yearly Issue Metrics
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Issue Metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERY: 'repo:holoviz/holoviews is:issue created:2025-01-01..2025-02-28 -label:"duplicate"'

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Yearly Issue Metrics Report
          token: ${{ secrets.GH_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: Azaya89
